[package]
name = "cobol-lexer"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "COBOL tokenizer supporting fixed and free format"

[dependencies]
cobol-intern = { workspace = true }
cobol-span = { workspace = true }
smol_str = { workspace = true }
